#############################################################################
# Kbuild file for 'SN9C1xx PC Camera Controllers' driver for Linux          #
#                                                                           #
#  Copyright (C) 2006-2008 by Luca Risolia <luca.risolia@studio.unibo.it>   #
#                                                                           #
#  This program is free software; you can redistribute it and/or modify     #
#  it under the terms of the GNU General Public License as published by     #
#  the Free Software Foundation; either version 2 of the License, or        #
#  (at your option) any later version.                                      #
#                                                                           #
#  This program is distributed in the hope that it will be useful,          #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#  GNU General Public License for more details.                             #
#                                                                           #
#  You should have received a copy of the GNU General Public License        #
#  along with this program; if not, write to the Free Software              #
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                #
#############################################################################

obj-m += sn9c102.o
sn9c102-objs := sn9c102_core.o \
                sensors/sn9c102_hv7131d.o \
                sensors/sn9c102_hv7131r.o \
                sensors/sn9c102_mi0343.o \
                sensors/sn9c102_mi0360.o \
                sensors/sn9c102_mt9v111.o \
                sensors/sn9c102_ov7630.o \
                sensors/sn9c102_ov7648.o \
                sensors/sn9c102_ov7660.o \
                sensors/sn9c102_pas106b.o \
                sensors/sn9c102_pas202bcb.o \
                sensors/sn9c102_tas5110c1b.o \
                sensors/sn9c102_tas5110d.o \
                sensors/sn9c102_tas5130d1b.o

# Enable the /sysfs interface overriding the kernel configuration option
EXTRA_CFLAGS := -DCONFIG_VIDEO_ADV_DEBUG
